In [3]:
import pandas as pd
import numpy as np

data = pd.read_csv('Sleep_health_and_lifestyle_dataset.csv')
# data.index()

TypeError: 'RangeIndex' object is not callable

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 374 entries, 0 to 373
Data columns (total 13 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   Person ID                374 non-null    int64  
 1   Gender                   374 non-null    object 
 2   Age                      374 non-null    int64  
 3   Occupation               374 non-null    object 
 4   Sleep Duration           374 non-null    float64
 5   Quality of Sleep         374 non-null    int64  
 6   Physical Activity Level  374 non-null    int64  
 7   Stress Level             374 non-null    int64  
 8   BMI Category             374 non-null    object 
 9   Blood Pressure           374 non-null    object 
 10  Heart Rate               374 non-null    int64  
 11  Daily Steps              374 non-null    int64  
 12  Sleep Disorder           374 non-null    object 
dtypes: float64(1), int64(7), object(5)
memory usage: 38.1+ KB


In [5]:
data.shape

(374, 13)

In [6]:
data.describe()

Person ID         Age  Sleep Duration  Quality of Sleep  \
count  374.000000  374.000000      374.000000        374.000000   
mean   187.500000   42.184492        7.132086          7.312834   
std    108.108742    8.673133        0.795657          1.196956   
min      1.000000   27.000000        5.800000          4.000000   
25%     94.250000   35.250000        6.400000          6.000000   
50%    187.500000   43.000000        7.200000          7.000000   
75%    280.750000   50.000000        7.800000          8.000000   
max    374.000000   59.000000        8.500000          9.000000   

       Physical Activity Level  Stress Level  Heart Rate   Daily Steps  
count               374.000000    374.000000  374.000000    374.000000  
mean                 59.171123      5.385027   70.165775   6816.844920  
std                  20.830804      1.774526    4.135676   1617.915679  
min                  30.000000      3.000000   65.000000   3000.000000  
25%                  45.000000      4.000000   68.000000   5600.000000  
50%                  60.000000      5.000000   70.000000   7000.000000  
75%                  75.000000      7.000000   72.000000   8000.000000  
max                  90.000000      8.000000   86.000000  10000.000000

In [11]:
data.set_index('Person ID', inplace=True)

KeyError: "None of ['Person ID'] are in the columns"

In [12]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 374 entries, 1 to 374
Data columns (total 12 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   Gender                   374 non-null    object 
 1   Age                      374 non-null    int64  
 2   Occupation               374 non-null    object 
 3   Sleep Duration           374 non-null    float64
 4   Quality of Sleep         374 non-null    int64  
 5   Physical Activity Level  374 non-null    int64  
 6   Stress Level             374 non-null    int64  
 7   BMI Category             374 non-null    object 
 8   Blood Pressure           374 non-null    object 
 9   Heart Rate               374 non-null    int64  
 10  Daily Steps              374 non-null    int64  
 11  Sleep Disorder           374 non-null    object 
dtypes: float64(1), int64(6), object(5)
memory usage: 38.0+ KB


In [13]:
data.describe()

Age  Sleep Duration  Quality of Sleep  Physical Activity Level  \
count  374.000000      374.000000        374.000000               374.000000   
mean    42.184492        7.132086          7.312834                59.171123   
std      8.673133        0.795657          1.196956                20.830804   
min     27.000000        5.800000          4.000000                30.000000   
25%     35.250000        6.400000          6.000000                45.000000   
50%     43.000000        7.200000          7.000000                60.000000   
75%     50.000000        7.800000          8.000000                75.000000   
max     59.000000        8.500000          9.000000                90.000000   

       Stress Level  Heart Rate   Daily Steps  
count    374.000000  374.000000    374.000000  
mean       5.385027   70.165775   6816.844920  
std        1.774526    4.135676   1617.915679  
min        3.000000   65.000000   3000.000000  
25%        4.000000   68.000000   5600.000000  
50%        5.000000   70.000000   7000.000000  
75%        7.000000   72.000000   8000.000000  
max        8.000000   86.000000  10000.000000

In [32]:
data['BMI Category'].unique()

array(['Overweight', 'Normal', 'Obese', 'Normal Weight'], dtype=object)

In [43]:
onehot_gender = pd.get_dummies(data['Gender'])
# onehot_gender
data = pd.concat([data, onehot_gender], axis = 1)

In [41]:
data.drop(['Male', 'Female'], axis = 1, inplace=True)

In [46]:
onehot_bmi = pd.get_dummies(data['BMI Category'])
data = pd.concat([data, onehot_bmi], axis = 1)

In [48]:
data.drop(['Gender', 'BMI Category'], axis=1, inplace=True)

In [148]:
onehot_target = pd.get_dummies(data['Sleep Disorder'])
data = pd.concat([data, onehot_target], axis=1)

In [150]:
data.drop(['Sleep Disorder'], axis=1, inplace=True)

In [151]:
data

Age            Occupation  Sleep Duration  Quality of Sleep  \
Person ID                                                                
1           27     Software Engineer             6.1                 6   
2           28                Doctor             6.2                 6   
3           28                Doctor             6.2                 6   
4           28  Sales Representative             5.9                 4   
5           28  Sales Representative             5.9                 4   
...        ...                   ...             ...               ...   
370         59                 Nurse             8.1                 9   
371         59                 Nurse             8.0                 9   
372         59                 Nurse             8.1                 9   
373         59                 Nurse             8.1                 9   
374         59                 Nurse             8.1                 9   

           Physical Activity Level  Stress Level Blood Pressure  Heart Rate  \
Person ID                                                                     
1                               42             6            126          77   
2                               60             8            126          75   
3                               60             8            126          75   
4                               30             8            126          85   
5                               30             8            126          85   
...                            ...           ...            ...         ...   
370                             75             3            126          68   
371                             75             3            126          68   
372                             75             3            126          68   
373                             75             3            126          68   
374                             75             3            126          68   

           Daily Steps  Female  Male  Normal  Normal Weight  Obese  \
Person ID                                                            
1                 4200       0     1       0              0      0   
2                10000       0     1       1              0      0   
3                10000       0     1       1              0      0   
4                 3000       0     1       0              0      1   
5                 3000       0     1       0              0      1   
...                ...     ...   ...     ...            ...    ...   
370               7000       1     0       0              0      0   
371               7000       1     0       0              0      0   
372               7000       1     0       0              0      0   
373               7000       1     0       0              0      0   
374               7000       1     0       0              0      0   

           Overweight  Insomnia  None  Sleep Apnea  
Person ID                                           
1                   1         0     1            0  
2                   0         0     1            0  
3                   0         0     1            0  
4                   0         0     0            1  
5                   0         0     0            1  
...               ...       ...   ...          ...  
370                 1         0     0            1  
371                 1         0     0            1  
372                 1         0     0            1  
373                 1         0     0            1  
374                 1         0     0            1  

[374 rows x 18 columns]

In [83]:
data.loc[:, 'Blood Pressure']

Person ID
1      126/83
2      125/80
3      125/80
4      140/90
5      140/90
        ...  
370    140/95
371    140/95
372    140/95
373    140/95
374    140/95
Name: Blood Pressure, Length: 374, dtype: object

In [126]:
data['Blood Pressure'][1].split('/')[0]

'126'

In [130]:
blood_data = data['Blood Pressure']
len(blood_data)
for i in range(1, len(blood_data)+1) :
    data['Blood Pressure'] = data['Blood Pressure'][i].split('/')[0]

In [131]:
data

Age            Occupation  Sleep Duration  Quality of Sleep  \
Person ID                                                                
1           27     Software Engineer             6.1                 6   
2           28                Doctor             6.2                 6   
3           28                Doctor             6.2                 6   
4           28  Sales Representative             5.9                 4   
5           28  Sales Representative             5.9                 4   
...        ...                   ...             ...               ...   
370         59                 Nurse             8.1                 9   
371         59                 Nurse             8.0                 9   
372         59                 Nurse             8.1                 9   
373         59                 Nurse             8.1                 9   
374         59                 Nurse             8.1                 9   

           Physical Activity Level  Stress Level Blood Pressure  Heart Rate  \
Person ID                                                                     
1                               42             6            126          77   
2                               60             8            126          75   
3                               60             8            126          75   
4                               30             8            126          85   
5                               30             8            126          85   
...                            ...           ...            ...         ...   
370                             75             3            126          68   
371                             75             3            126          68   
372                             75             3            126          68   
373                             75             3            126          68   
374                             75             3            126          68   

           Daily Steps Sleep Disorder  Female  Male  Normal  Normal Weight  \
Person ID                                                                    
1                 4200           None       0     1       0              0   
2                10000           None       0     1       1              0   
3                10000           None       0     1       1              0   
4                 3000    Sleep Apnea       0     1       0              0   
5                 3000    Sleep Apnea       0     1       0              0   
...                ...            ...     ...   ...     ...            ...   
370               7000    Sleep Apnea       1     0       0              0   
371               7000    Sleep Apnea       1     0       0              0   
372               7000    Sleep Apnea       1     0       0              0   
373               7000    Sleep Apnea       1     0       0              0   
374               7000    Sleep Apnea       1     0       0              0   

           Obese  Overweight  
Person ID                     
1              0           1  
2              0           0  
3              0           0  
4              1           0  
5              1           0  
...          ...         ...  
370            0           1  
371            0           1  
372            0           1  
373            0           1  
374            0           1  

[374 rows x 16 columns]

In [132]:
sleep_train = data[['Female', 'Male', 'Age', 'Sleep Duration', 'Quality of Sleep', 'Physical Activity Level', 'Stress Level', 'Normal', 'Normal Weight', 'Obese', 'Overweight', 'Blood Pressure', 'Heart Rate', 'Daily Steps']].to_numpy()
sleep_train

array([[0, 1, 27, ..., '126', 77, 4200],
       [0, 1, 28, ..., '126', 75, 10000],
       [0, 1, 28, ..., '126', 75, 10000],
       ...,
       [1, 0, 59, ..., '126', 68, 7000],
       [1, 0, 59, ..., '126', 68, 7000],
       [1, 0, 59, ..., '126', 68, 7000]], dtype=object)

In [152]:
sleep_target = data[['Insomnia', 'None', 'Sleep Apnea']].to_numpy()
sleep_target

array([[0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       ...,
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1]], dtype=uint8)

In [153]:
from sklearn.model_selection import train_test_split

train_input, test_input, train_target, test_target = train_test_split(sleep_train, sleep_target, random_state=42)

In [154]:
train_input

array([[0, 1, 44, ..., '126', 72, 6000],
       [0, 1, 44, ..., '126', 72, 6000],
       [0, 1, 38, ..., '126', 68, 8000],
       ...,
       [1, 0, 49, ..., '126', 75, 10000],
       [1, 0, 57, ..., '126', 68, 7000],
       [1, 0, 36, ..., '126', 68, 7000]], dtype=object)

In [155]:
test_input

array([[1, 0, 53, ..., '126', 65, 5000],
       [0, 1, 31, ..., '126', 72, 5000],
       [0, 1, 29, ..., '126', 70, 8000],
       ...,
       [0, 1, 32, ..., '126', 72, 5000],
       [0, 1, 39, ..., '126', 68, 8000],
       [1, 0, 53, ..., '126', 65, 5000]], dtype=object)

In [156]:
from sklearn.preprocessing import StandardScaler

ss = StandardScaler()
ss.fit(train_input)

StandardScaler()

In [157]:
train_scaled = ss.transform(train_input)
test_scaled = ss.transform(test_input)

In [143]:
train_scaled[:5]

array([[-1.04381619,  1.04381619,  0.17265472, -1.08260812, -1.15283871,
        -0.73085692,  0.96057491, -1.02899151, -0.24618298, -0.14797909,
         1.20670641,  0.        ,  0.47516158, -0.55224501],
       [-1.04381619,  1.04381619,  0.17265472, -1.08260812, -1.15283871,
        -0.73085692,  0.96057491, -1.02899151, -0.24618298, -0.14797909,
         1.20670641,  0.        ,  0.47516158, -0.55224501],
       [-1.04381619,  1.04381619, -0.53653825, -0.06325453,  0.55056413,
        -0.00995531, -0.1766808 ,  0.97182532, -0.24618298, -0.14797909,
        -0.82870199,  0.        , -0.50853707,  0.69980845],
       [-1.04381619,  1.04381619, -1.6003277 , -1.46486572, -1.15283871,
        -1.45175853,  1.52920276,  0.97182532, -0.24618298, -0.14797909,
        -0.82870199,  0.        , -0.01668775,  0.69980845],
       [-1.04381619,  1.04381619,  0.17265472, -1.08260812, -1.15283871,
        -0.73085692,  0.96057491, -1.02899151, -0.24618298, -0.14797909,
         1.20670641,  0.  

In [144]:
test_scaled[:5]

array([[ 0.95802308, -0.95802308,  1.23644416,  1.72061425,  1.40226556,
        -1.45175853, -1.31393651,  0.97182532, -0.24618298, -0.14797909,
        -0.82870199,  0.        , -1.24631107, -1.17827174],
       [-1.04381619,  1.04381619, -1.36393004, -1.33744652, -1.15283871,
        -1.45175853,  1.52920276,  0.97182532, -0.24618298, -0.14797909,
        -0.82870199,  0.        ,  0.47516158, -1.17827174],
       [-1.04381619,  1.04381619, -1.6003277 , -1.46486572, -1.15283871,
        -1.45175853,  1.52920276,  0.97182532, -0.24618298, -0.14797909,
        -0.82870199,  0.        , -0.01668775,  0.69980845],
       [ 0.95802308, -0.95802308,  1.23644416,  1.72061425,  1.40226556,
        -1.45175853, -1.31393651,  0.97182532, -0.24618298, -0.14797909,
        -0.82870199,  0.        , -1.24631107, -1.17827174],
       [-1.04381619,  1.04381619, -1.24573122, -1.46486572, -1.15283871,
        -1.45175853,  1.52920276,  0.97182532, -0.24618298, -0.14797909,
        -0.82870199,  0.  

In [158]:
from sklearn.linear_model import LinearRegression

lr = LinearRegression()

lr.fit(train_scaled, train_target)

LinearRegression()

In [159]:
print(lr.score(train_scaled, train_target))
print(lr.score(test_scaled, test_target))

0.5763788640973013
0.5383372604326054


In [160]:
lr2 = LinearRegression()

lr2.fit(train_input, train_target)

LinearRegression()

In [162]:
print(lr2.score(train_input, train_target))
print(lr2.score(test_input, test_target))

0.5763788640973013
0.5383372604325892


In [164]:
train_input, train_scaled

(array([[0, 1, 44, ..., '126', 72, 6000],
        [0, 1, 44, ..., '126', 72, 6000],
        [0, 1, 38, ..., '126', 68, 8000],
        ...,
        [1, 0, 49, ..., '126', 75, 10000],
        [1, 0, 57, ..., '126', 68, 7000],
        [1, 0, 36, ..., '126', 68, 7000]], dtype=object),
 array([[-1.04381619,  1.04381619,  0.17265472, ...,  0.        ,
          0.47516158, -0.55224501],
        [-1.04381619,  1.04381619,  0.17265472, ...,  0.        ,
          0.47516158, -0.55224501],
        [-1.04381619,  1.04381619, -0.53653825, ...,  0.        ,
         -0.50853707,  0.69980845],
        ...,
        [ 0.95802308, -0.95802308,  0.76364885, ...,  0.        ,
          1.21293558,  1.95186192],
        [ 0.95802308, -0.95802308,  1.70923948, ...,  0.        ,
         -0.50853707,  0.07378172],
        [ 0.95802308, -0.95802308, -0.7729359 , ...,  0.        ,
         -0.50853707,  0.07378172]]))