In [125]:
import pandas as pd

sleep = pd.read_csv('Sleep_health_and_lifestyle_dataset.csv')
sleep

Person ID  Gender  Age            Occupation  Sleep Duration  \
0            1    Male   27     Software Engineer             6.1   
1            2    Male   28                Doctor             6.2   
2            3    Male   28                Doctor             6.2   
3            4    Male   28  Sales Representative             5.9   
4            5    Male   28  Sales Representative             5.9   
..         ...     ...  ...                   ...             ...   
369        370  Female   59                 Nurse             8.1   
370        371  Female   59                 Nurse             8.0   
371        372  Female   59                 Nurse             8.1   
372        373  Female   59                 Nurse             8.1   
373        374  Female   59                 Nurse             8.1   

     Quality of Sleep  Physical Activity Level  Stress Level BMI Category  \
0                   6                       42             6   Overweight   
1                   6                       60             8       Normal   
2                   6                       60             8       Normal   
3                   4                       30             8        Obese   
4                   4                       30             8        Obese   
..                ...                      ...           ...          ...   
369                 9                       75             3   Overweight   
370                 9                       75             3   Overweight   
371                 9                       75             3   Overweight   
372                 9                       75             3   Overweight   
373                 9                       75             3   Overweight   

    Blood Pressure  Heart Rate  Daily Steps Sleep Disorder  
0           126/83          77         4200           None  
1           125/80          75        10000           None  
2           125/80          75        10000           None  
3           140/90          85         3000    Sleep Apnea  
4           140/90          85         3000    Sleep Apnea  
..             ...         ...          ...            ...  
369         140/95          68         7000    Sleep Apnea  
370         140/95          68         7000    Sleep Apnea  
371         140/95          68         7000    Sleep Apnea  
372         140/95          68         7000    Sleep Apnea  
373         140/95          68         7000    Sleep Apnea  

[374 rows x 13 columns]

In [126]:
sleep_df = sleep[['Gender', 'Age', 'Sleep Duration', 'Quality of Sleep', 'Physical Activity Level', 'Stress Level', 'BMI Category', 'Blood Pressure', 'Heart Rate', 'Daily Steps', 'Sleep Disorder' ]].to_numpy()
sleep_df

array([['Male', 27, 6.1, ..., 77, 4200, 'None'],
       ['Male', 28, 6.2, ..., 75, 10000, 'None'],
       ['Male', 28, 6.2, ..., 75, 10000, 'None'],
       ...,
       ['Female', 59, 8.1, ..., 68, 7000, 'Sleep Apnea'],
       ['Female', 59, 8.1, ..., 68, 7000, 'Sleep Apnea'],
       ['Female', 59, 8.1, ..., 68, 7000, 'Sleep Apnea']], dtype=object)

In [127]:
y = sleep[['Sleep Disorder']]

In [128]:
onehot_y = pd.get_dummies(y['Sleep Disorder'])
y = pd.concat([y, onehot_y], axis=1)

y.drop(['Sleep Disorder'], axis=1, inplace=True)
y.head()

Insomnia  None  Sleep Apnea
0         0     1            0
1         0     1            0
2         0     1            0
3         0     0            1
4         0     0            1

In [129]:
y_np = y.to_numpy()
y_np

array([[0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       ...,
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1]], dtype=uint8)

In [130]:
x = sleep[['Age', 'Sleep Duration', 'Quality of Sleep', 'Physical Activity Level', 'Blood Pressure','Stress Level', 'BMI Category', 'Heart Rate', 'Daily Steps']]


In [131]:
# BMI지수 - 원핫인코딩

In [132]:
onehot_x = pd.get_dummies(x['BMI Category'])
x = pd.concat([x, onehot_x], axis=1)

x.drop(['BMI Category'], axis=1, inplace=True)
x.head()

Age  Sleep Duration  Quality of Sleep  Physical Activity Level  \
0   27             6.1                 6                       42   
1   28             6.2                 6                       60   
2   28             6.2                 6                       60   
3   28             5.9                 4                       30   
4   28             5.9                 4                       30   

  Blood Pressure  Stress Level  Heart Rate  Daily Steps  Normal  \
0         126/83             6          77         4200       0   
1         125/80             8          75        10000       1   
2         125/80             8          75        10000       1   
3         140/90             8          85         3000       0   
4         140/90             8          85         3000       0   

   Normal Weight  Obese  Overweight  
0              0      0           1  
1              0      0           0  
2              0      0           0  
3              0      1           0  
4              0      1           0

In [133]:
x_np = x.to_numpy()
x_np

array([[27, 6.1, 6, ..., 0, 0, 1],
       [28, 6.2, 6, ..., 0, 0, 0],
       [28, 6.2, 6, ..., 0, 0, 0],
       ...,
       [59, 8.1, 9, ..., 0, 0, 1],
       [59, 8.1, 9, ..., 0, 0, 1],
       [59, 8.1, 9, ..., 0, 0, 1]], dtype=object)

In [134]:
for i in range(len(x_np)) :
    for j in range(len(x_np[0])) :
        if j == 4 :
            a,b = x_np[i][j].split('/')
            x_np[i][j] = int(a)

In [135]:
x_np[0]

array([27, 6.1, 6, 42, 126, 6, 77, 4200, 0, 0, 0, 1], dtype=object)

In [136]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x_np, y_np, train_size=0.9, test_size=0.1)


In [137]:
from sklearn.neighbors import KNeighborsRegressor

knr = KNeighborsRegressor(n_neighbors = 3)
knr.fit(x_train, y_train)

KNeighborsRegressor(n_neighbors=3)

In [138]:
print(knr.score(x_train, y_train))
print(knr.score(x_test, y_test))

0.7508362662796534
0.6460157126823792
